Vipa\WorkflowBundle\Entity\ArticleWorkflow:
  type: entity
  table: bc_wf_article_workflow
  repositoryClass: Vipa\WorkflowBundle\Entity\ArticleWorkflowRepository
  type: entity
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    startDate:
      column: 'start_date'
      type: datetime
      nullable: false
    status:
      type: integer
      nullable: false
      options:
        default: 1
    reviewVersionFile:
      type: string
      nullable: true
  manyToOne:
    journal:
      targetEntity: Vipa\JournalBundle\Entity\Journal
      joinColumn:
        name: journal_id
        referencedColumnName: id
    article:
      targetEntity: Vipa\JournalBundle\Entity\Article
      joinColumn:
        name: article_id
        referencedColumnName: id
    currentStep:
      targetEntity: Vipa\WorkflowBundle\Entity\ArticleWorkflowStep
      joinColumn:
        name: current_step_id
        referencedColumnName: id
  oneToMany:
    steps:
      targetEntity: Vipa\WorkflowBundle\Entity\ArticleWorkflowStep
      mappedBy: articleWorkflow
  manyToMany:
    grantedUsers:
      targetEntity: Vipa\UserBundle\Entity\User
      joinTable:
        name: bc_article_wf_user
        joinColumns:
          step_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
    relatedUsers:
      targetEntity: Vipa\UserBundle\Entity\User
      joinTable:
        name: bc_wf_article_workflow_related_users
        joinColumns:
          article_workflow_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
  lifecycleCallbacks: {}
