vipa_workflow:
    resource: "routing/workflow.yml"
    prefix:   /journal/{journalId}/workflow/

vipa_workflow_review_form:
    resource: "routing/journal_review_form.yml"
    prefix:   /journal/{journalId}/workflow/{stepId}/review-form

vipa_workflow_export_review_form:
    resource: "routing/export_review_form.yml"
    prefix:   /journal/{journalId}/export/review-form

vipa_workflow_step:
    resource: "routing/wf_setting.yml"
    prefix:   /journal/{journalId}/workflow-setting/

vipa_workflow_article_workflow:
    resource: "routing/article_workflow.yml"
    prefix:   /journal/{journalId}/article-workflow/

vipa_workflow_restart:
    resource: "routing/restart_workflow.yml"
    prefix:   /journal/{journalId}/restart-workflow

vipa_workflow_article:
    resource: "routing/article.yml"
    prefix:   /journal/{journalId}/article

vipa_workflow_users:
    resource: "routing/users.yml"
    prefix:   /journal/{journalId}/workflow/{workflowId}/users
