services:
  vipa.workflow_extension:
    class: Vipa\WorkflowBundle\Service\Twig\DPWorkflowTwigExtension
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@translator"
      - "@vipa.journal_service"
      - "@security.token_storage"
      - "@session"
      - "@request_stack"
      - "@event_dispatcher"
      - "@dp.workflow_permission_service"
      - "@twig"
    tags:
      - { name: twig.extension }

  dp.workflow.left_menu_listener:
    class: Vipa\WorkflowBundle\EventListener\LeftMenuListener
    arguments:
      - "@security.authorization_checker"
      - "@vipa.journal_service"
      - "@dp.workflow_permission_service"
    tags:
      - { name: kernel.event_subscriber }

  dp.workflow_service:
    class: Vipa\WorkflowBundle\Service\WorkflowService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@vipa.journal_service"
      - "@security.token_storage"
      - "@dp.wf_logger_service"
      - "@dp.workflow_permission_service"
      - "@translator"
      - "@twig"
      - "@event_dispatcher"

  dp.workflow_permission_service:
    class: Vipa\WorkflowBundle\Service\WorkflowPermissionService
    arguments:
      - "@vipa.journal_service"
      - "@security.token_storage"
      - "@doctrine.orm.entity_manager"

  dp.wf_logger_service:
    class: Vipa\WorkflowBundle\Service\WorkflowLoggerService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@vipa.journal_service"
      - "@translator"

  dp.workflow.article_submit_event_listener:
    class: Vipa\WorkflowBundle\EventListener\ArticleSubmitEventListener
    arguments: ["@dp.workflow_service"]
    tags:
      - { name: kernel.event_subscriber }

  dp_workflow.workflow_events:
    class: Vipa\WorkflowBundle\Event\WorkflowEvents
    tags:
      - { name: vipa.mail.event}

  dp.worklfow.mail_listener:
    class: Vipa\WorkflowBundle\EventListener\WorkflowMailListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@vipa_mailer", "@translator"]
    tags:
      - { name: kernel.event_subscriber }

  dp.worklfow.article_list_event_listener:
    class: Vipa\WorkflowBundle\EventListener\ArticleListEventListener
    arguments: ["@vipa.journal_service", "@doctrine.orm.entity_manager", "@router", "@translator"]
    tags:
      - { name: kernel.event_subscriber }

  dp.workflow_export_grid_action:
    class: Vipa\WorkflowBundle\Service\ExportGridAction
    arguments: ["@translator"]

  dp.worklfow.article_crud_listener:
    class: Vipa\WorkflowBundle\EventListener\ArticleCrudListener
    arguments: ["@doctrine.orm.entity_manager", "@dp.workflow_service"]
    tags:
      - { name: kernel.event_subscriber }

  dp.worklfow.merge_user_listener:
    class: Ojs\WorkflowBundle\EventListener\MergeUserListener
    arguments: ["@doctrine.orm.entity_manager", "@dp.workflow_service"]
    tags:
      - { name: kernel.event_subscriber }