dp_workflow_step_dialogs:
  path:     /get/dialogs
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:getDialogs" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_create_specific_dialog:
  path:     /create/spesific-dialog
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:createSpecificDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_create_dialog_with_author:
  path:     /create/author-dialog
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:createDialogWithAuthor" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_create_basic_dialog:
  path:     /create/basic-dialog
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:createBasicDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true


dp_workflow_create_assign_reviewer_dialog:
  path:     /create/assign-reviewer-dialog
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:createAssignReviewerDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_accept_goto_arrangement:
  path:     /accept/goto-arrangement
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:acceptGotoArrangement" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_goto_reviewing:
  path:     /goto-reviewing
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:gotoReviewing" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_accept_submission:
  path:     /accept-submission
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:acceptSubmission" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_decline_submission:
  path:     /decline-submission
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:declineSubmission" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_finish_workflow:
  path:     /finish-workflow
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:finishWorkflow" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_finish:
  path:     /finish-dialog/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:finishDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_reopen:
  path:     /reopen-dialog/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:reopenDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_remove:
  path:     /remove-dialog/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:removeDialog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_invite_reviewer:
  path:     /invite-reviewer/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:inviteReviewer" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_remind_reviewer:
  path:     /remind-reviewer/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:remindReviewer" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_accept_review:
  path:     /accept-review/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:acceptReview" }
  options:
      expose: true

dp_workflow_dialog_reject_review:
  path:     /reject-review/{dialogId}
  defaults: { _controller: "VipaWorkflowBundle:StepDialog:rejectReview" }
  options:
      expose: true
