vipa_workflow_reviewers_browse:
  path:     /browse-reviewers
  defaults: { _controller: "VipaWorkflowBundle:Users:browseReviewers" }
  options:
      expose: true

vipa_workflow_section_editors_browse:
  path:     /browse-section-editors
  defaults: { _controller: "VipaWorkflowBundle:Users:browseSectionEditors" }
  options:
      expose: true

vipa_workflow_create_reviewer_user:
  path:     /create-reviewer-user
  defaults: { _controller: "VipaWorkflowBundle:Users:createReviewerUser" }
  options:
      expose: true

vipa_workflow_add_reviewer_user:
  path:     /add-reviewer-user
  defaults: { _controller: "VipaWorkflowBundle:Users:addReviewerUser" }
  options:
      expose: true
