vipa_workflow_step_index:
  path:     /
  defaults: { _controller: "VipaWorkflowBundle:WorkflowSetting:index" }

vipa_workflow_basic_settings:
  path:     /basic-setting
  defaults: { _controller: "VipaWorkflowBundle:WorkflowSetting:basicSetting" }
  condition: "request.isXmlHttpRequest()"

vipa_workflow_step_users_setup:
  path:     /step-users-setup/{stepOrder}
  defaults: { _controller: "VipaWorkflowBundle:WorkflowSetting:stepUsersSetup" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true
