vipa_workflow_flow_active:
  path:     /active
  defaults: { _controller: "VipaWorkflowBundle:Workflow:actives" }
  options:
    expose: true

vipa_workflow_flow_history:
  path:     /history
  defaults: { _controller: "VipaWorkflowBundle:Workflow:history" }
